default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.13.5"
    hooks:
      - id: pylint
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: [ "--load-plugins=pylint_django", "--django-settings-module=app" ]
        additional_dependencies: [
            django,
            pylint_django,
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies: [
            djangorestframework-stubs,
            django-stubs,
        ]
